Repository sobeeLOG/back-end, pull requests merged in 2023-06, with the labels that each got.

#14 feat:✨ 소비 내역의 전체 댓글 조회 GET 기능 추가
  .github/ISSUE_TEMPLATE/feature-생성-등록.md
  constants/responseMessage.js
  controllers/comment/commentDELETE.js
  controllers/comment/commentGET.js
  controllers/comment/commentPOST.js
  models/comment.js
  models/index.js
  routes/comment/index.js
  routes/index.js
Labels: :kiwi_fruit: feature

#17 feat:✨ 댓글 작성 POST 기능 추가
  controllers/comment/commentPOST.js
  models/comment.js
  routes/comment/index.js
Labels: :kiwi_fruit: feature

#26 feat:✨ 댓글 수정 PUT 기능 추가
  constants/responseMessage.js
  controllers/comment/commentDELETE.js
  controllers/comment/commentEDIT.js
  models/comment.js
  routes/comment/index.js
Labels: :kiwi_fruit: feature

#36 feat:✨ 좋아요/싫어요 공감하기 POST 기능 추가
  constants/responseMessage.js
  controllers/emoticon/emoticonPOST
  models/emoticon.js
  models/index.js
  routes/emoticon/index
  routes/index.js
Labels: :kiwi_fruit: feature

#38 feat:✨ 좋아요/싫어요 공감 취소하기 DELETE 추가
  constants/responseMessage.js
  controllers/emoticon/emoticonDELETE
  models/emoticon.js
  routes/emoticon/index.js
Labels: :kiwi_fruit: feature

#41 feat:✨ 댓글 작성 POST 조건 추가
  constants/responseMessage.js
  controllers/comment/commentPOST.js
  controllers/emoticon/emoticonDELETE.js
  controllers/emoticon/emoticonPOST.js
  models/comment.js
Labels: :kiwi_fruit: feature

#15 feat: ✨ 친구 닉네임 검색 GET 기능 추가
  constants/responseMessage.js
  controllers/friends/findUserListGET.js
  models/friends.js
  models/index.js
  routes/friends/index.js
Labels: :kiwi_fruit: feature

#44 bug: 🐛친구 신청 중복 요청 문제 해결
  constants/responseMessage.js
  controllers/friends/findUserListGET.js
  controllers/friends/friendRequestPOST.js
  controllers/friends/myFriendsListGET.js
  controllers/friends/receivedFriendRequestsListGET.js
Labels: 🛠 fix

#46 feat: ✨ date 포함한 소비내역 POST 기능 추가
  controllers/consumptionHistory/consumptionHistoryPOST.js
  models/consumptionHistory.js
  routes/index.js
Labels: :kiwi_fruit: feature

#47 [FEATURE] [GET] 총 지출 조회
  constants/responseMessage.js
  controllers/mycalendar/totalConsumptionAmountGET.js
  models/calendar.js
  routes/mycalendar/index.js
Labels: :kiwi_fruit: feature

#49 feat: ✨ 아이디별 소비내역 조회 기능 추가
  constants/responseMessage.js
  controllers/consumptionHistory/consumptionHistoryGET.js
  models/calendar.js
  models/consumptionHistory.js
  routes/consumptionHistory/index.js
Labels: :kiwi_fruit: feature

#52 feat:✨ 로그인 POST 기능 추가
  app.js
  constants/responseMessage.js
  controllers/auth/loginPOST.js
  models/auth.js
  models/index.js
  package.json
  routes/auth/index.js
  routes/index.js
Labels: :kiwi_fruit: feature

#56 bug: 🐛 이모티콘 수 가져오기, DELETE 수정
  constants/responseMessage.js
  controllers/consumptionHistory/consumptionHistoryGET.js
  controllers/emoticon/emoticonDELETE.js
  models/calendar.js
  models/emoticon.js
Labels: 🚨 bug

#58 fix: 🔨 사용자 검색 조건 추가
  controllers/friends/findUserListGET.js
  models/friends.js
Labels: 🛠 fix
